[env:genericSTM32F103VE]
platform = ststm32
board = genericSTM32F103VE
framework = arduino
upload_protocol = stlink
debug_tool = stlink
build_flags = 
	-D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	-D USBCON
	-D USBD_VID=0x0483
	-D USBD_PID=0x5740
	-D HAL_PCD_MODULE_ENABLED
lib_deps =
    SoftwareSerial
